---
apiVersion: v1
kind: Namespace
metadata:
  name: demo-priv
  labels:
    pod-security.kubernetes.io/enforce: privileged
    pod-security.kubernetes.io/enforce-version: v1.24
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: privileged-deployment
  namespace: demo-priv
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app-priv
  template:
    metadata:
      labels:
        app: app-priv
    spec:
      containers:
        - image: busybox
          name: busybox
          command: ["sh", "-c", 'while true; do echo "Running..."; sleep 2h; done']
          imagePullPolicy: Always
          securityContext:
            privileged: true
            runAsUser: 0
            allowPrivilegeEscalation: true
            readOnlyRootFilesystem: false
            capabilities:
              add: ["CAP_SYS_BOOT"]
