---
apiVersion: v1
kind: Namespace
metadata:
  name: demo-warn
  labels:
    pod-security.kubernetes.io/enforce: baseline
    pod-security.kubernetes.io/enforce-version: v1.24
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-deployment
  namespace: demo-warn
spec:
  replicas: 1
  selector:
    matchLabels:
      app: busybox
  template:
    metadata:
      labels:
        app: busybox
    spec:
      containers:
        - name: demo-enforce
          image: busybox
          command: ["sh", "-c", 'while true; do echo "Running..."; sleep 2h; done']
          imagePullPolicy: Always
          securityContext:
            privileged: false
            capabilities:
              add: ["CHOWN"]
